// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjNK-aDUhM_FDK_gsKbn6KUu9GYfePgL8',
    appId: '1:937489643638:web:6a391e9ee4266495c7c757',
    messagingSenderId: '937489643638',
    projectId: 'computer-platform-5fe23',
    authDomain: 'computer-platform-5fe23.firebaseapp.com',
    storageBucket: 'computer-platform-5fe23.appspot.com',
    measurementId: 'G-L2XZQ8F7NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd9Hh8wd9lqVEj0vZHAw9xphK5onwfSiQ',
    appId: '1:937489643638:android:a787c501f455e5ddc7c757',
    messagingSenderId: '937489643638',
    projectId: 'computer-platform-5fe23',
    storageBucket: 'computer-platform-5fe23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE79TCITkSDDs8yLkEtWhfKIgia5BwlqI',
    appId: '1:937489643638:ios:bd93a2df609618d7c7c757',
    messagingSenderId: '937489643638',
    projectId: 'computer-platform-5fe23',
    storageBucket: 'computer-platform-5fe23.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE79TCITkSDDs8yLkEtWhfKIgia5BwlqI',
    appId: '1:937489643638:ios:bd93a2df609618d7c7c757',
    messagingSenderId: '937489643638',
    projectId: 'computer-platform-5fe23',
    storageBucket: 'computer-platform-5fe23.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjNK-aDUhM_FDK_gsKbn6KUu9GYfePgL8',
    appId: '1:937489643638:web:ceaeea371dbac4b5c7c757',
    messagingSenderId: '937489643638',
    projectId: 'computer-platform-5fe23',
    authDomain: 'computer-platform-5fe23.firebaseapp.com',
    storageBucket: 'computer-platform-5fe23.appspot.com',
    measurementId: 'G-BGHQHTJ67B',
  );

}